-- 1. Création des profils  
CREATE PROFILE profil_agent_vente LIMIT
SESSIONS_PER_USER 10
CPU_PER_SESSION UNLIMITED
CPU_PER_CALL 60000
CONNECT_TIME 480
IDLE_TIME 15
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_LIFE_TIME 30;

CREATE PROFILE profil_client_app LIMIT
SESSIONS_PER_USER 100
CPU_PER_SESSION UNLIMITED
CPU_PER_CALL 30000
CONNECT_TIME 1440
IDLE_TIME 30
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_LIFE_TIME 90;

CREATE PROFILE profil_admin_transport LIMIT
SESSIONS_PER_USER 20
CPU_PER_SESSION UNLIMITED
CPU_PER_CALL UNLIMITED
CONNECT_TIME UNLIMITED
IDLE_TIME 60
FAILED_LOGIN_ATTEMPTS 10
PASSWORD_LIFE_TIME 45;

