-- 2. Création des utilisateurs avec quotas adaptés
CREATE USER agent_vente IDENTIFIED BY AgentVente2025
DEFAULT TABLESPACE TS_BILLETS
TEMPORARY TABLESPACE temp
PROFILE profil_agent_vente
QUOTA 10M ON TS_BILLETS
QUOTA 10M ON TS_PAIEMENTS
QUOTA 5M ON TS_CLIENTS
ACCOUNT UNLOCK;

CREATE USER client_app IDENTIFIED BY ClientApp2025
DEFAULT TABLESPACE TS_BILLETS
TEMPORARY TABLESPACE temp
PROFILE profil_client_app
QUOTA 20M ON TS_BILLETS
QUOTA 20M ON TS_PAIEMENTS
QUOTA 10M ON TS_CLIENTS
ACCOUNT UNLOCK;

CREATE USER admin_transport IDENTIFIED BY Admin2025
DEFAULT TABLESPACE TS_ARCHIVE
TEMPORARY TABLESPACE temp
PROFILE profil_admin_transport
QUOTA UNLIMITED ON TS_BILLETS
QUOTA UNLIMITED ON TS_PAIEMENTS
QUOTA UNLIMITED ON TS_CLIENTS
QUOTA UNLIMITED ON TS_ARCHIVE
ACCOUNT UNLOCK;

-- 3. Attribution des privilèges
GRANT CREATE SESSION TO agent_vente;
GRANT SELECT, INSERT, UPDATE, DELETE ON BILLETS TO agent_vente;
GRANT SELECT, INSERT ON PAIEMENTS TO agent_vente;
GRANT SELECT ON CLIENTS TO agent_vente;

GRANT CREATE SESSION TO client_app;
GRANT SELECT, INSERT ON BILLETS TO client_app;
GRANT SELECT, INSERT ON PAIEMENTS TO client_app;
GRANT SELECT ON CLIENTS TO client_app;

GRANT DBA TO admin_transport;
GRANT ALL PRIVILEGES ON CLIENTS TO admin_transport;
GRANT ALL PRIVILEGES ON BILLETS TO admin_transport;
GRANT ALL PRIVILEGES ON PAIEMENTS TO admin_transport;
GRANT ALL PRIVILEGES ON ARCHIVE_VOYAGES TO admin_transport;
