-- Table des clients
CREATE TABLE CLIENTS (
    id_client NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR2(50),
    prenom VARCHAR2(50),
    email VARCHAR2(100),
    telephone VARCHAR2(20)
) TABLESPACE TS_CLIENTS;

-- Table des billets (Réservations)
CREATE TABLE BILLETS (
    id_billet NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_client NUMBER,
    date_depart TIMESTAMP,
    ville_depart VARCHAR2(50),
    ville_arrivee VARCHAR2(50),
    prix NUMBER(8,2),
    statut VARCHAR2(20), -- 'CONFIRME', 'ATTENTE', 'ANNULE'
    CONSTRAINT fk_client FOREIGN KEY (id_client) REFERENCES CLIENTS(id_client)
) TABLESPACE TS_BILLETS;

-- Table des paiements
CREATE TABLE PAIEMENTS (
    id_paiement NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_billet NUMBER,
    date_paiement TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    montant NUMBER(8,2),
    mode_paiement VARCHAR2(30), -- 'CARTE', 'ESPECES'
    CONSTRAINT fk_billet FOREIGN KEY (id_billet) REFERENCES BILLETS(id_billet)
) TABLESPACE TS_PAIEMENTS;

-- Table d'archive (pour les vieux trajets)
CREATE TABLE ARCHIVE_VOYAGES (
    id_archive NUMBER PRIMARY KEY,
    details_voyage CLOB,
    date_archivage DATE DEFAULT SYSDATE
) TABLESPACE TS_ARCHIVE;
